version: "3"

services:
  db:
    image:  postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: cocoa_db
